# Generated by Django 5.2.16 on 2026-07-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_listing_removal_reason_alter_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(max_length=10),
        ),
    ]
