# Generated by Django 5.2.16 on 2026-07-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], default='NEW', max_length=10),
        ),
    ]
