# Generated by Django 5.2.16 on 2026-07-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_listing_phone_number_listing_whatsapp_number'),
        ('marketplace', '0005_alter_listing_condition'),
    ]

    operations = [
    ]
