# Generated by Django 5.2.17 on 2026-09-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_hostel_hostelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='removal_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Moderation'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
