# Generated by Django 5.2.17 on 2026-09-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_hostel_removal_reason_hostel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_quick_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='quick_sale_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
