# Generated by Django 5.2.16 on 2026-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for calls (e.g. +256700000000)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number (e.g. +256700000000)', max_length=20, null=True),
        ),
    ]
