# Generated by Django 5.2.17 on 2026-09-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_buyermembership_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('QUICK_SALE', 'Quick Sale')], max_length=10, unique=True),
        ),
    ]
